import { useMemo, useState } from 'react';
import { useAppStore } from '../../context/AppStore';

const readPreference = (key: string) => window.localStorage.getItem(key) === 'true';
export function SettingsPage() {
  const { snapshot, resetSnapshot } = useAppStore(); const [freeChoice, setFreeChoice] = useState(() => readPreference('family-learning:free-choice')); const [eyeCare, setEyeCare] = useState(() => readPreference('family-learning:eye-care')); const [feedback, setFeedback] = useState('');
  const size = useMemo(() => `${(JSON.stringify(snapshot).length / 1024).toFixed(1)} KB`, [snapshot]);
  const toggle = (key: string, value: boolean, setValue: (value: boolean) => void) => { setValue(value); window.localStorage.setItem(key, String(value)); };
  return <div className="parent-page"><div className="page-heading"><div><p className="eyebrow">工作台偏好</p><h1>设置</h1><p className="page-subtitle">这些偏好只保存在当前浏览器中。</p></div></div>{feedback && <p className="success-message" role="status">{feedback}</p>}<div className="settings-grid"><section className="panel"><div className="panel-heading"><div><h2>本地数据</h2><p>学习数据保存在浏览器 localStorage，不会上传服务器。</p></div></div><div className="storage-meter"><span className="metric-icon blue">▣</span><div><strong data-testid="storage-size">{size}</strong><small>当前估算占用</small></div></div><button type="button" className="button danger-outline" onClick={() => { resetSnapshot(); setFeedback('演示数据已恢复'); }}>恢复演示数据</button></section><section className="panel"><div className="panel-heading"><div><h2>儿童端偏好</h2><p>下次打开儿童端时继续使用。</p></div></div><label className="setting-toggle"><span><strong>允许自由选课</strong><small>儿童可浏览所有已发布课程</small></span><input type="checkbox" checked={freeChoice} onChange={(event) => toggle('family-learning:free-choice', event.target.checked, setFreeChoice)} /></label><label className="setting-toggle"><span><strong>护眼模式</strong><small>降低儿童端的对比度和亮度</small></span><input type="checkbox" checked={eyeCare} onChange={(event) => toggle('family-learning:eye-care', event.target.checked, setEyeCare)} /></label></section></div></div>;
}
