import { useEffect, useRef, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ProgressBar } from '../../components/ProgressBar';
import { StatusBadge } from '../../components/StatusBadge';
import { useAppStore } from '../../context/AppStore';
import { naturalCompare } from '../../lib/domain';
import { type UploadTask } from '../../types/domain';

type LocalTask = UploadTask & { file?: File };
const accepted = (name: string) => /\.(mp4|mov)$/i.test(name);
const taskStatus: Record<UploadTask['status'], string> = { QUEUED: '排队中', UPLOADING: '上传中', COMPLETED: '已完成', CANCELLED: '已取消', FAILED: '失败' };

export function UploadsPage() {
  const { courses, addVideo } = useAppStore(); const location = useLocation(); const presetCourse = new URLSearchParams(location.search).get('course') ?? '';
  const [courseId, setCourseId] = useState(presetCourse); const [tasks, setTasks] = useState<LocalTask[]>([]); const [error, setError] = useState(''); const inputRef = useRef<HTMLInputElement>(null); const filesRef = useRef<Record<string, File>>({}); const addedTaskIds = useRef(new Set<string>()); const failedTaskIds = useRef(new Set<string>());
  useEffect(() => { const timer = window.setInterval(() => { setTasks((current) => current.map((task) => { if (task.status !== 'QUEUED' && task.status !== 'UPLOADING') return task; const nextProgress = Math.min(100, task.progress + 14); if (task.fileName.toLowerCase().includes('fail') && nextProgress >= 56 && !failedTaskIds.current.has(task.id)) { failedTaskIds.current.add(task.id); return { ...task, status: 'FAILED', progress: nextProgress, error: '模拟网络中断，请重试' }; } if (nextProgress >= 100) return { ...task, status: 'COMPLETED', progress: 100 }; return { ...task, status: 'UPLOADING', progress: nextProgress }; })); }, 120); return () => window.clearInterval(timer); }, []);
  useEffect(() => { tasks.filter((task) => task.status === 'COMPLETED' && !addedTaskIds.current.has(task.id)).forEach((task) => { addedTaskIds.current.add(task.id); addVideo(task.courseId, { title: task.fileName.replace(/\.(mp4|mov)$/i, ''), fileName: task.fileName, durationSeconds: 180, status: 'READY' }); }); }, [tasks, addVideo]);
  const enqueue = (incoming: FileList | File[]) => { setError(''); if (!courseId) { setError('请先选择所属课程'); return; } const files = Array.from(incoming); const invalid = files.find((file) => !accepted(file.name)); if (invalid) { setError(`“${invalid.name}”格式不支持，仅支持 MP4 / MOV。`); return; } const next = files.sort((a, b) => naturalCompare(a.name, b.name)).map((file, index) => { const id = `upload-${Date.now()}-${index}`; filesRef.current[id] = file; return { id, courseId, fileName: file.name, progress: 0, status: 'QUEUED' as const, file }; }); setTasks((current) => [...current, ...next].sort((a, b) => naturalCompare(a.fileName, b.fileName))); };
  const retry = (task: LocalTask) => setTasks((current) => current.map((item) => item.id === task.id ? { ...item, status: 'QUEUED', progress: 0, error: undefined } : item));
  const cancel = (task: LocalTask) => setTasks((current) => current.map((item) => item.id === task.id && (item.status === 'QUEUED' || item.status === 'UPLOADING') ? { ...item, status: 'CANCELLED' } : item));
  return <div className="parent-page"><div className="page-heading"><div><p className="eyebrow">媒体内容</p><h1>视频上传</h1><p className="page-subtitle">一次选择多段视频，上传完成后自动进入课程目录。</p></div><Link to="/parent/courses" className="button">返回课程管理</Link></div><div className="upload-layout"><section className="upload-drop panel" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); enqueue(event.dataTransfer.files); }} onClick={() => inputRef.current?.click()}><div className="upload-orbit">↑</div><h2>拖拽视频到这里</h2><p>或点击选择文件，支持一次选择多个视频</p><small>仅支持 MP4、MOV 格式</small><input ref={inputRef} type="file" accept=".mp4,.mov,video/mp4,video/quicktime" multiple hidden onChange={(event) => { if (event.target.files) enqueue(event.target.files); event.target.value = ''; }} /></section><section className="panel upload-settings"><div className="panel-heading"><div><h2>上传设置</h2><p>完成的视频会以 READY 状态写入课程。</p></div></div><label>所属课程<select aria-label="所属课程" value={courseId} onChange={(event) => setCourseId(event.target.value)}><option value="">请选择课程</option>{courses.map((course) => <option value={course.id} key={course.id}>{course.title}</option>)}</select></label>{error && <p className="form-error" role="alert">{error}</p>}</section></div>{tasks.length > 0 && <section className="panel upload-queue"><div className="panel-heading"><div><h2>上传队列</h2><p>{tasks.filter((task) => task.status === 'COMPLETED').length} / {tasks.length} 个文件已完成</p></div></div><div className="task-list">{tasks.map((task) => <div className="upload-task" key={task.id}><div className="task-file"><span className="file-mark">▣</span><div><strong>{task.fileName}</strong><small>{taskStatus[task.status]}{task.error ? ` · ${task.error}` : ''}</small></div></div><ProgressBar value={task.progress / 100} label={`${task.fileName} 上传进度`} /><StatusBadge status={task.status === 'UPLOADING' ? 'UPLOADING' : task.status === 'FAILED' ? 'FAILED' : task.status === 'COMPLETED' ? 'READY' : 'DRAFT'} /><div className="task-actions">{task.status === 'FAILED' && <button type="button" onClick={() => retry(task)}>重试</button>}{(task.status === 'QUEUED' || task.status === 'UPLOADING') && <button type="button" onClick={() => cancel(task)}>取消</button>}</div></div>)}</div></section>}</div>;
}
