import { useEffect, useRef, useState, type KeyboardEvent } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ProgressBar } from '../../components/ProgressBar';
import { useAppStore } from '../../context/AppStore';
import { naturalCompare } from '../../lib/domain';
import { type UploadTask } from '../../types/domain';

const accepted = (name: string) => /\.(mp4|mov)$/i.test(name);
const taskStatus: Record<UploadTask['status'], string> = { QUEUED: '排队中', UPLOADING: '上传中', COMPLETED: '已完成', CANCELLED: '已取消', FAILED: '失败' };
const UPLOAD_STEP = 0.14;
const SIMULATED_FAILURE_PROGRESS = 0.56;

export function UploadsPage() {
  const { courses, uploadTasks, createUploadTask, updateUploadTask, completeUploadTask } = useAppStore(); const location = useLocation(); const presetCourse = new URLSearchParams(location.search).get('course') ?? '';
  const [courseId, setCourseId] = useState(presetCourse); const [error, setError] = useState(''); const inputRef = useRef<HTMLInputElement>(null); const taskRef = useRef(uploadTasks); const progressRef = useRef<Record<string, number>>({}); const updateTaskRef = useRef(updateUploadTask); const completeTaskRef = useRef(completeUploadTask); const failedTaskIds = useRef(new Set<string>());
  taskRef.current = uploadTasks; updateTaskRef.current = updateUploadTask; completeTaskRef.current = completeUploadTask;
  useEffect(() => { const timer = window.setInterval(() => { taskRef.current.filter((task) => (task.status === 'QUEUED' || task.status === 'UPLOADING') && !failedTaskIds.current.has(task.id)).forEach((task) => { const nextProgress = Math.min(1, (progressRef.current[task.id] ?? task.progress) + UPLOAD_STEP); progressRef.current[task.id] = nextProgress; if (task.fileName.toLowerCase().includes('fail') && nextProgress >= SIMULATED_FAILURE_PROGRESS) { failedTaskIds.current.add(task.id); updateTaskRef.current(task.id, { status: 'FAILED', progress: nextProgress, error: '模拟网络中断，请重试' }); } else if (nextProgress >= 1) updateTaskRef.current(task.id, { status: 'COMPLETED', progress: 1, error: undefined }); else updateTaskRef.current(task.id, { status: 'UPLOADING', progress: nextProgress }); }); }, 120); return () => window.clearInterval(timer); }, []);
  useEffect(() => { uploadTasks.filter((task) => task.status === 'COMPLETED' && !task.videoId).forEach((task) => { completeTaskRef.current(task.id, { title: task.fileName.replace(/\.(mp4|mov)$/i, ''), durationSeconds: 180 }); }); }, [uploadTasks]);
  const enqueue = (incoming: FileList | File[]) => { if (!courseId) { setError('请先选择所属课程'); return; } const files = Array.from(incoming); const invalid = files.filter((file) => !accepted(file.name)); const valid = files.filter((file) => accepted(file.name)).sort((a, b) => naturalCompare(a.name, b.name)); setError(invalid.length ? `${invalid.map((file) => `“${file.name}”`).join('、')}格式不支持，仅支持 MP4 / MOV。` : ''); valid.forEach((file) => createUploadTask({ courseId, fileName: file.name })); };
  const retry = (task: UploadTask) => { progressRef.current[task.id] = 0; failedTaskIds.current.delete(task.id); updateUploadTask(task.id, { status: 'QUEUED', progress: 0, error: undefined }); };
  const cancel = (task: UploadTask) => updateUploadTask(task.id, { status: 'CANCELLED' });
  const openFilePicker = () => inputRef.current?.click();
  const handleDropZoneKeyDown = (event: KeyboardEvent<HTMLElement>) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openFilePicker(); } };
  return <div className="parent-page"><div className="page-heading"><div><p className="eyebrow">媒体内容</p><h1>视频上传</h1><p className="page-subtitle">一次选择多段视频，上传完成后自动进入课程目录。</p></div><Link to="/parent/courses" className="button">返回课程管理</Link></div><div className="upload-layout"><section className="upload-drop panel" role="button" tabIndex={0} aria-label="选择视频文件" onKeyDown={handleDropZoneKeyDown} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); enqueue(event.dataTransfer.files); }} onClick={openFilePicker}><div className="upload-orbit">↑</div><h2>拖拽视频到这里</h2><p>或点击选择文件，支持一次选择多个视频</p><small>仅支持 MP4、MOV 格式</small><input ref={inputRef} type="file" accept=".mp4,.mov,video/mp4,video/quicktime" multiple hidden onClick={(event) => event.stopPropagation()} onChange={(event) => { if (event.target.files) enqueue(event.target.files); event.target.value = ''; }} /></section><section className="panel upload-settings"><div className="panel-heading"><div><h2>上传设置</h2><p>完成的视频会以 READY 状态写入课程。</p></div></div><label>所属课程<select aria-label="所属课程" value={courseId} onChange={(event) => setCourseId(event.target.value)}><option value="">请选择课程</option>{courses.map((course) => <option value={course.id} key={course.id}>{course.title}</option>)}</select></label>{error && <p className="form-error" role="alert">{error}</p>}</section></div>{uploadTasks.length > 0 && <section className="panel upload-queue"><div className="panel-heading"><div><h2>上传队列</h2><p>{uploadTasks.filter((task) => task.status === 'COMPLETED').length} / {uploadTasks.length} 个文件已完成</p></div></div><div className="task-list">{[...uploadTasks].sort((a, b) => naturalCompare(a.fileName, b.fileName)).map((task) => <div className="upload-task" key={task.id}><div className="task-file"><span className="file-mark">▣</span><div><strong>{task.fileName}</strong><small>{taskStatus[task.status]}{task.error ? ` · ${task.error}` : ''}</small></div></div><ProgressBar value={task.progress} label={`${task.fileName} 上传进度`} /><span className={`status-badge task-status task-${task.status.toLowerCase()}`}>{taskStatus[task.status]}</span><div className="task-actions">{task.status === 'FAILED' && <button type="button" onClick={() => retry(task)}>重试</button>}{(task.status === 'QUEUED' || task.status === 'UPLOADING') && <button type="button" onClick={() => cancel(task)}>取消</button>}</div></div>)}</div></section>}</div>;
}
