ALTER TABLE "Child"
ADD COLUMN "avatar" TEXT NOT NULL DEFAULT '🌟',
ADD COLUMN "grade" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Course"
ADD COLUMN "ageRange" TEXT NOT NULL DEFAULT '',
ADD COLUMN "coverStyle" TEXT NOT NULL DEFAULT 'sunrise';
